testDijkstra (__main__.TestAlgo) ... FAIL
testIndiceMinimum (__main__.TestAlgo) ... FAIL
testNoeudMinimalNonVisitesDeNoeudA (__main__.TestAlgo) ... FAIL
testNoeudMinimalNonVisitesDeNoeudB (__main__.TestAlgo) ... FAIL
testNoeudsVoisinsA (__main__.TestAlgo) ... FAIL
testNoeudsVoisinsB (__main__.TestAlgo) ... FAIL
testnoeudMinimalNonVisites (__main__.TestAlgo) ... FAIL
testCarteEnSommets (__main__.TestCarte) ... ERROR
testDistance3D (__main__.TestCarte) ... ERROR
testDistanceEuclidienne (__main__.TestCarte) ... ERROR
testEstVoisinA (__main__.TestCarte) ... ok
testEstVoisinB (__main__.TestCarte) ... FAIL
testMatriceAdjacence (__main__.TestCarte) ... ERROR
testChargeMatriceDeCarte (__main__.TestFichier) ... FAIL
testLireCarte (__main__.TestFichier) ... FAIL
testAfficheChemin (__main__.TestInterface) ... FAIL
testGenereMatriceAleatoireA (__main__.TestInterface) ... FAIL
testGenereMatriceAleatoireB (__main__.TestInterface) ... ERROR
testSaisirMatrice (__main__.TestInterface) ... FAIL

======================================================================
ERROR: testCarteEnSommets (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 142, in testCarteEnSommets
    carteTopographique = carte_data_ex["carte_topo"]
KeyError: 'carte_topo'

======================================================================
ERROR: testDistance3D (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 133, in testDistance3D
    self.assertEqual(distance, carte_data_ex["dist_3D"])
KeyError: 'dist_3D'

======================================================================
ERROR: testDistanceEuclidienne (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 127, in testDistanceEuclidienne
    self.assertEqual(distance, carte_data_ex["dist_eu"])
KeyError: 'dist_eu'

======================================================================
ERROR: testMatriceAdjacence (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 138, in testMatriceAdjacence
    matrice_2 = carte_data_ex["matrice_ad"]
KeyError: 'matrice_ad'

======================================================================
ERROR: testGenereMatriceAleatoireB (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 172, in testGenereMatriceAleatoireB
    for i, ligne in enumerate(matrice):
TypeError: 'ellipsis' object is not iterable

======================================================================
FAIL: testDijkstra (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 108, in testDijkstra
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testIndiceMinimum (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 62, in testIndiceMinimum
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudMinimalNonVisitesDeNoeudA (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 70, in testNoeudMinimalNonVisitesDeNoeudA
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudMinimalNonVisitesDeNoeudB (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 78, in testNoeudMinimalNonVisitesDeNoeudB
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudsVoisinsA (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 93, in testNoeudsVoisinsA
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudsVoisinsB (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 100, in testNoeudsVoisinsB
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testnoeudMinimalNonVisites (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 85, in testnoeudMinimalNonVisites
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testEstVoisinB (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 121, in testEstVoisinB
    self.assertFalse(estVoisin(sommet1, sommet2))
AssertionError: Ellipsis is not false

======================================================================
FAIL: testChargeMatriceDeCarte (__main__.TestFichier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 156, in testChargeMatriceDeCarte
    self.assertListEqual(carte, fichier_data_ex["carte_2"])
AssertionError: First sequence is not a list: Ellipsis

======================================================================
FAIL: testLireCarte (__main__.TestFichier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 151, in testLireCarte
    self.assertListEqual(carte, fichier_data_ex["carte_1"])
AssertionError: First sequence is not a list: Ellipsis

======================================================================
FAIL: testAfficheChemin (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 186, in testAfficheChemin
    self.assertMultiLineEqual(interface_data_ex["txt"], txt)
AssertionError: Ellipsis is not an instance of <class 'str'> : Second argument is not a string

======================================================================
FAIL: testGenereMatriceAleatoireA (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 166, in testGenereMatriceAleatoireA
    self.assertTrue(isinstance(genereMatriceAleatoire(5), list))
AssertionError: False is not true

======================================================================
FAIL: testSaisirMatrice (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "test_assignment.py", line 163, in testSaisirMatrice
    self.assertListEqual(saisirMatrice(), matrice)
AssertionError: First sequence is not a list: Ellipsis

----------------------------------------------------------------------
Ran 19 tests in 0.037s

FAILED (failures=13, errors=5)
